// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AspIT.NorthwindApp.CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Selects an employee, changes the first name and then presses the save button
        /// </summary>
        public void EditEmployeeTest1()
        {
            #region Variable Declarations
            WpfControl uIItemDataItem = this.UIEmployeeOverwatchWindow.UIEmployeeListTable.UIItemDataItem;
            WpfEdit uIFirstNameTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIFirstNameTbEdit;
            WpfButton uIGemændringerButton = this.UIEmployeeOverwatchWindow.UIGemændringerButton;
            #endregion

            // Click DataItem
            Mouse.Click(uIItemDataItem, new Point(1265, 42));

            // Click 'firstNameTb' text box
            Mouse.Click(uIFirstNameTbEdit, new Point(49, 6));

            // Type 'Control + {Back}' in 'firstNameTb' text box
            Keyboard.SendKeys(uIFirstNameTbEdit, this.EditEmployeeTest1Params.UIFirstNameTbEditSendKeys, ModifierKeys.Control);

            // Type 'Paulie' in 'firstNameTb' text box
            uIFirstNameTbEdit.Text = this.EditEmployeeTest1Params.UIFirstNameTbEditText;

            // Type '{Enter}' in 'firstNameTb' text box
            Keyboard.SendKeys(uIFirstNameTbEdit, this.EditEmployeeTest1Params.UIFirstNameTbEditSendKeys1, ModifierKeys.None);

            // Click 'Gem ændringer' button
            Mouse.Click(uIGemændringerButton, new Point(43, 12));
        }
        
        /// <summary>
        /// Selects an employee, changes some data and then presses the save button
        /// </summary>
        public void EditEmployeeTest2()
        {
            #region Variable Declarations
            WpfControl uIItemDataItem1 = this.UIEmployeeOverwatchWindow.UIEmployeeListTable.UIItemDataItem1;
            WpfDatePicker uIBirthDatePickerDatePicker = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIBirthDatePickerDatePicker;
            WpfEdit uICountryTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICountryTbEdit;
            WpfEdit uITitleTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UITitleTbEdit;
            WpfButton uIGemændringerButton = this.UIEmployeeOverwatchWindow.UIGemændringerButton;
            #endregion

            // Click DataItem numbered 3 in 'employeeList' table
            Mouse.Click(uIItemDataItem1, new Point(631, 34));

            // Select '14-Aug-1963' in 'birthDatePicker' date picker
            uIBirthDatePickerDatePicker.DateAsString = this.EditEmployeeTest2Params.UIBirthDatePickerDatePickerDateAsString;

            // Type 'UK' in 'countryTb' text box
            uICountryTbEdit.Text = this.EditEmployeeTest2Params.UICountryTbEditText;

            // Type 'Marketing' in 'titleTb' text box
            uITitleTbEdit.Text = this.EditEmployeeTest2Params.UITitleTbEditText;

            // Click 'Gem ændringer' button
            Mouse.Click(uIGemændringerButton, new Point(15, 17));
        }
        
        /// <summary>
        /// Selects an employee, changes the city. Then presses the save button
        /// </summary>
        public void EditEmployeeTest3()
        {
            #region Variable Declarations
            WpfCell uIItem999Cell = this.UIEmployeeOverwatchWindow.UIEmployeeListTable.UIItemDataItem2.UIItem999Cell;
            WpfEdit uIAddressTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIAddressTbEdit;
            WpfEdit uIRegionTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIRegionTbEdit;
            WpfEdit uICityTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICityTbEdit;
            WpfButton uIGemændringerButton = this.UIEmployeeOverwatchWindow.UIGemændringerButton;
            #endregion

            // Click '999' cell
            Mouse.Click(uIItem999Cell, new Point(0, 14));

            // Type 'Tavern 29' in 'addressTb' text box
            uIAddressTbEdit.Text = this.EditEmployeeTest3Params.UIAddressTbEditText;

            // Click 'regionTb' text box
            Mouse.Click(uIRegionTbEdit, new Point(69, 13));

            // Type 'Control + {Back}' in 'regionTb' text box
            Keyboard.SendKeys(uIRegionTbEdit, this.EditEmployeeTest3Params.UIRegionTbEditSendKeys, ModifierKeys.Control);

            // Click 'cityTb' text box
            Mouse.Click(uICityTbEdit, new Point(85, 10));

            // Click 'Gem ændringer' button
            Mouse.Click(uIGemændringerButton, new Point(82, 20));
        }
        
        /// <summary>
        /// Selects an employee and presses the delete button
        /// </summary>
        public void DeleteEmployeeTest1()
        {
            #region Variable Declarations
            WpfControl uIItemDataItem3 = this.UIEmployeeOverwatchWindow.UIEmployeeListTable.UIItemDataItem3;
            WpfButton uISletButton = this.UIEmployeeOverwatchWindow.UISletButton;
            #endregion

            // Click DataItem numbered 11 in 'employeeList' table
            Mouse.Click(uIItemDataItem3, new Point(1000, 45));

            // Click 'Slet' button
            Mouse.Click(uISletButton, new Point(22, 19));
        }
        
        /// <summary>
        /// Fills all information and presses the add button
        /// </summary>
        public void AddEmployeeTest1()
        {
            #region Variable Declarations
            WpfComboBox uIComboBoxComboBox = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIComboBoxComboBox;
            WpfEdit uIFirstNameTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIFirstNameTbEdit;
            WpfEdit uILastNameTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UILastNameTbEdit;
            WpfDatePicker uIBirthDatePickerDatePicker = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIBirthDatePickerDatePicker;
            WpfEdit uIAddressTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIAddressTbEdit;
            WpfEdit uICityTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICityTbEdit;
            WpfEdit uIRegionTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIRegionTbEdit;
            WpfEdit uIPostalCodeTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIPostalCodeTbEdit;
            WpfEdit uICountryTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICountryTbEdit;
            WpfEdit uIHomePhoneTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIHomePhoneTbEdit;
            WpfEdit uITitleTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UITitleTbEdit;
            WpfDatePicker uIHireDatePickerDatePicker = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIHireDatePickerDatePicker;
            WpfEdit uIExtensionTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIExtensionTbEdit;
            WpfEdit uINotesTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UINotesTbEdit;
            WpfEdit uIReportsToTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIReportsToTbEdit;
            WpfButton uITilføjButton = this.UIEmployeeOverwatchWindow.UITilføjButton;
            #endregion

            // Select 'Mr.' in 'comboBox' combo box
            uIComboBoxComboBox.SelectedItem = this.AddEmployeeTest1Params.UIComboBoxComboBoxSelectedItem;

            // Type 'John' in 'firstNameTb' text box
            uIFirstNameTbEdit.Text = this.AddEmployeeTest1Params.UIFirstNameTbEditText;

            // Type '{Tab}' in 'firstNameTb' text box
            Keyboard.SendKeys(uIFirstNameTbEdit, this.AddEmployeeTest1Params.UIFirstNameTbEditSendKeys, ModifierKeys.None);

            // Type 'Crayon' in 'lastNameTb' text box
            uILastNameTbEdit.Text = this.AddEmployeeTest1Params.UILastNameTbEditText;

            // Select '19-Jul-1979' in 'birthDatePicker' date picker
            uIBirthDatePickerDatePicker.DateAsString = this.AddEmployeeTest1Params.UIBirthDatePickerDatePickerDateAsString;

            // Type 'Crowstreet 13' in 'addressTb' text box
            uIAddressTbEdit.Text = this.AddEmployeeTest1Params.UIAddressTbEditText;

            // Type 'Clove city' in 'cityTb' text box
            uICityTbEdit.Text = this.AddEmployeeTest1Params.UICityTbEditText;

            // Type '{Tab}' in 'cityTb' text box
            Keyboard.SendKeys(uICityTbEdit, this.AddEmployeeTest1Params.UICityTbEditSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'regionTb' text box
            Keyboard.SendKeys(uIRegionTbEdit, this.AddEmployeeTest1Params.UIRegionTbEditSendKeys, ModifierKeys.None);

            // Type '9291' in 'postalCodeTb' text box
            uIPostalCodeTbEdit.Text = this.AddEmployeeTest1Params.UIPostalCodeTbEditText;

            // Type '{Tab}' in 'postalCodeTb' text box
            Keyboard.SendKeys(uIPostalCodeTbEdit, this.AddEmployeeTest1Params.UIPostalCodeTbEditSendKeys, ModifierKeys.None);

            // Type 'Bland' in 'countryTb' text box
            uICountryTbEdit.Text = this.AddEmployeeTest1Params.UICountryTbEditText;

            // Type '{Tab}' in 'countryTb' text box
            Keyboard.SendKeys(uICountryTbEdit, this.AddEmployeeTest1Params.UICountryTbEditSendKeys, ModifierKeys.None);

            // Type '9229222' in 'homePhoneTb' text box
            uIHomePhoneTbEdit.Text = this.AddEmployeeTest1Params.UIHomePhoneTbEditText;

            // Type '{Tab}' in 'homePhoneTb' text box
            Keyboard.SendKeys(uIHomePhoneTbEdit, this.AddEmployeeTest1Params.UIHomePhoneTbEditSendKeys, ModifierKeys.None);

            // Type 'Haybale Representive' in 'titleTb' text box
            uITitleTbEdit.Text = this.AddEmployeeTest1Params.UITitleTbEditText;

            // Type '{Tab}' in 'titleTb' text box
            Keyboard.SendKeys(uITitleTbEdit, this.AddEmployeeTest1Params.UITitleTbEditSendKeys, ModifierKeys.None);

            // Select '07-Sep-2010' in 'hireDatePicker' date picker
            uIHireDatePickerDatePicker.DateAsString = this.AddEmployeeTest1Params.UIHireDatePickerDatePickerDateAsString;

            // Type '2399' in 'extensionTb' text box
            uIExtensionTbEdit.Text = this.AddEmployeeTest1Params.UIExtensionTbEditText;

            // Type 'John is a crazy man from clove city' in 'notesTb' text box
            uINotesTbEdit.Text = this.AddEmployeeTest1Params.UINotesTbEditText;

            // Type '' in 'reportsToTb' text box
            uIReportsToTbEdit.Text = this.AddEmployeeTest1Params.UIReportsToTbEditText;

            // Type '{Tab}' in 'reportsToTb' text box
            Keyboard.SendKeys(uIReportsToTbEdit, this.AddEmployeeTest1Params.UIReportsToTbEditSendKeys, ModifierKeys.None);

            // Click 'Tilføj' button
            Mouse.Click(uITilføjButton, new Point(16, 16));
        }
        
        /// <summary>
        /// Adds an employee from scratch
        /// </summary>
        public void AddEmployeeTest2()
        {
            #region Variable Declarations
            WpfComboBox uIComboBoxComboBox = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIComboBoxComboBox;
            WpfEdit uIFirstNameTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIFirstNameTbEdit;
            WpfEdit uILastNameTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UILastNameTbEdit;
            WpfDatePicker uIBirthDatePickerDatePicker = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIBirthDatePickerDatePicker;
            WpfGroup uIPersonligeoplysningeGroup = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup;
            WpfEdit uIAddressTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIAddressTbEdit;
            WpfEdit uICityTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICityTbEdit;
            WpfEdit uIRegionTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIRegionTbEdit;
            WpfEdit uIPostalCodeTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIPostalCodeTbEdit;
            WpfEdit uICountryTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UICountryTbEdit;
            WpfEdit uIHomePhoneTbEdit = this.UIEmployeeOverwatchWindow.UIPersonligeoplysningeGroup.UIHomePhoneTbEdit;
            WpfEdit uITitleTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UITitleTbEdit;
            WpfDatePicker uIHireDatePickerDatePicker = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIHireDatePickerDatePicker;
            WpfEdit uIExtensionTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIExtensionTbEdit;
            WpfEdit uIReportsToTbEdit = this.UIEmployeeOverwatchWindow.UIAndreoplysningerGroup.UIReportsToTbEdit;
            WpfButton uITilføjButton = this.UIEmployeeOverwatchWindow.UITilføjButton;
            #endregion

            // Click 'comboBox' combo box
            Mouse.Click(uIComboBoxComboBox, new Point(54, 9));

            // Click 'comboBox' combo box
            Mouse.Click(uIComboBoxComboBox, new Point(80, 7));

            // Type 'Jole' in 'firstNameTb' text box
            uIFirstNameTbEdit.Text = this.AddEmployeeTest2Params.UIFirstNameTbEditText;

            // Type '{Tab}' in 'firstNameTb' text box
            Keyboard.SendKeys(uIFirstNameTbEdit, this.AddEmployeeTest2Params.UIFirstNameTbEditSendKeys, ModifierKeys.None);

            // Type 'Smack' in 'lastNameTb' text box
            uILastNameTbEdit.Text = this.AddEmployeeTest2Params.UILastNameTbEditText;

            // Select '11-Sep-1984' in 'birthDatePicker' date picker
            uIBirthDatePickerDatePicker.DateAsString = this.AddEmployeeTest2Params.UIBirthDatePickerDatePickerDateAsString;

            // Click 'Personlige oplysninger' group
            Mouse.Click(uIPersonligeoplysningeGroup, new Point(150, 223));

            // Type 'Crayon. 21street' in 'addressTb' text box
            uIAddressTbEdit.Text = this.AddEmployeeTest2Params.UIAddressTbEditText;

            // Click 'addressTb' text box
            Mouse.Click(uIAddressTbEdit, new Point(46, 10));

            // Type 'Melon City' in 'cityTb' text box
            uICityTbEdit.Text = this.AddEmployeeTest2Params.UICityTbEditText;

            // Type '{Tab}' in 'cityTb' text box
            Keyboard.SendKeys(uICityTbEdit, this.AddEmployeeTest2Params.UICityTbEditSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'regionTb' text box
            Keyboard.SendKeys(uIRegionTbEdit, this.AddEmployeeTest2Params.UIRegionTbEditSendKeys, ModifierKeys.None);

            // Type '8219' in 'postalCodeTb' text box
            uIPostalCodeTbEdit.Text = this.AddEmployeeTest2Params.UIPostalCodeTbEditText;

            // Type '{Tab}' in 'postalCodeTb' text box
            Keyboard.SendKeys(uIPostalCodeTbEdit, this.AddEmployeeTest2Params.UIPostalCodeTbEditSendKeys, ModifierKeys.None);

            // Type 'Ma land' in 'countryTb' text box
            uICountryTbEdit.Text = this.AddEmployeeTest2Params.UICountryTbEditText;

            // Type '{Tab}' in 'countryTb' text box
            Keyboard.SendKeys(uICountryTbEdit, this.AddEmployeeTest2Params.UICountryTbEditSendKeys, ModifierKeys.None);

            // Type '2891828283838281838' in 'homePhoneTb' text box
            uIHomePhoneTbEdit.Text = this.AddEmployeeTest2Params.UIHomePhoneTbEditText;

            // Type '{Tab}' in 'homePhoneTb' text box
            Keyboard.SendKeys(uIHomePhoneTbEdit, this.AddEmployeeTest2Params.UIHomePhoneTbEditSendKeys, ModifierKeys.None);

            // Double-Click 'homePhoneTb' text box
            Mouse.DoubleClick(uIHomePhoneTbEdit, new Point(77, 20));

            // Type 'Melon Representive' in 'titleTb' text box
            uITitleTbEdit.Text = this.AddEmployeeTest2Params.UITitleTbEditText;

            // Select '05-Jul-2017' in 'hireDatePicker' date picker
            uIHireDatePickerDatePicker.DateAsString = this.AddEmployeeTest2Params.UIHireDatePickerDatePickerDateAsString;

            // Type '818' in 'extensionTb' text box
            uIExtensionTbEdit.Text = this.AddEmployeeTest2Params.UIExtensionTbEditText;

            // Type '{Tab}' in 'extensionTb' text box
            Keyboard.SendKeys(uIExtensionTbEdit, this.AddEmployeeTest2Params.UIExtensionTbEditSendKeys, ModifierKeys.None);

            // Type '{Tab}' in 'reportsToTb' text box
            Keyboard.SendKeys(uIReportsToTbEdit, this.AddEmployeeTest2Params.UIReportsToTbEditSendKeys, ModifierKeys.None);

            // Click 'Tilføj' button
            Mouse.Click(uITilføjButton, new Point(29, 16));
        }
        
        #region Properties
        public virtual EditEmployeeTest1Params EditEmployeeTest1Params
        {
            get
            {
                if ((this.mEditEmployeeTest1Params == null))
                {
                    this.mEditEmployeeTest1Params = new EditEmployeeTest1Params();
                }
                return this.mEditEmployeeTest1Params;
            }
        }
        
        public virtual EditEmployeeTest2Params EditEmployeeTest2Params
        {
            get
            {
                if ((this.mEditEmployeeTest2Params == null))
                {
                    this.mEditEmployeeTest2Params = new EditEmployeeTest2Params();
                }
                return this.mEditEmployeeTest2Params;
            }
        }
        
        public virtual EditEmployeeTest3Params EditEmployeeTest3Params
        {
            get
            {
                if ((this.mEditEmployeeTest3Params == null))
                {
                    this.mEditEmployeeTest3Params = new EditEmployeeTest3Params();
                }
                return this.mEditEmployeeTest3Params;
            }
        }
        
        public virtual AddEmployeeTest1Params AddEmployeeTest1Params
        {
            get
            {
                if ((this.mAddEmployeeTest1Params == null))
                {
                    this.mAddEmployeeTest1Params = new AddEmployeeTest1Params();
                }
                return this.mAddEmployeeTest1Params;
            }
        }
        
        public virtual AddEmployeeTest2Params AddEmployeeTest2Params
        {
            get
            {
                if ((this.mAddEmployeeTest2Params == null))
                {
                    this.mAddEmployeeTest2Params = new AddEmployeeTest2Params();
                }
                return this.mAddEmployeeTest2Params;
            }
        }
        
        public UIEmployeeOverwatchWindow UIEmployeeOverwatchWindow
        {
            get
            {
                if ((this.mUIEmployeeOverwatchWindow == null))
                {
                    this.mUIEmployeeOverwatchWindow = new UIEmployeeOverwatchWindow();
                }
                return this.mUIEmployeeOverwatchWindow;
            }
        }
        #endregion
        
        #region Fields
        private EditEmployeeTest1Params mEditEmployeeTest1Params;
        
        private EditEmployeeTest2Params mEditEmployeeTest2Params;
        
        private EditEmployeeTest3Params mEditEmployeeTest3Params;
        
        private AddEmployeeTest1Params mAddEmployeeTest1Params;
        
        private AddEmployeeTest2Params mAddEmployeeTest2Params;
        
        private UIEmployeeOverwatchWindow mUIEmployeeOverwatchWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditEmployeeTest1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class EditEmployeeTest1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Control + {Back}' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditSendKeys = "{Back}";
        
        /// <summary>
        /// Type 'Paulie' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditText = "Paulie";
        
        /// <summary>
        /// Type '{Enter}' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditSendKeys1 = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditEmployeeTest2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class EditEmployeeTest2Params
    {
        
        #region Fields
        /// <summary>
        /// Select '14-Aug-1963' in 'birthDatePicker' date picker
        /// </summary>
        public string UIBirthDatePickerDatePickerDateAsString = "14-Aug-1963";
        
        /// <summary>
        /// Type 'UK' in 'countryTb' text box
        /// </summary>
        public string UICountryTbEditText = "UK";
        
        /// <summary>
        /// Type 'Marketing' in 'titleTb' text box
        /// </summary>
        public string UITitleTbEditText = "Marketing";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditEmployeeTest3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class EditEmployeeTest3Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Tavern 29' in 'addressTb' text box
        /// </summary>
        public string UIAddressTbEditText = "Tavern 29";
        
        /// <summary>
        /// Type 'Control + {Back}' in 'regionTb' text box
        /// </summary>
        public string UIRegionTbEditSendKeys = "{Back}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddEmployeeTest1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddEmployeeTest1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'Mr.' in 'comboBox' combo box
        /// </summary>
        public string UIComboBoxComboBoxSelectedItem = "Mr.";
        
        /// <summary>
        /// Type 'John' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditText = "John";
        
        /// <summary>
        /// Type '{Tab}' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Crayon' in 'lastNameTb' text box
        /// </summary>
        public string UILastNameTbEditText = "Crayon";
        
        /// <summary>
        /// Select '19-Jul-1979' in 'birthDatePicker' date picker
        /// </summary>
        public string UIBirthDatePickerDatePickerDateAsString = "19-Jul-1979";
        
        /// <summary>
        /// Type 'Crowstreet 13' in 'addressTb' text box
        /// </summary>
        public string UIAddressTbEditText = "Crowstreet 13";
        
        /// <summary>
        /// Type 'Clove city' in 'cityTb' text box
        /// </summary>
        public string UICityTbEditText = "Clove city";
        
        /// <summary>
        /// Type '{Tab}' in 'cityTb' text box
        /// </summary>
        public string UICityTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'regionTb' text box
        /// </summary>
        public string UIRegionTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '9291' in 'postalCodeTb' text box
        /// </summary>
        public string UIPostalCodeTbEditText = "9291";
        
        /// <summary>
        /// Type '{Tab}' in 'postalCodeTb' text box
        /// </summary>
        public string UIPostalCodeTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Bland' in 'countryTb' text box
        /// </summary>
        public string UICountryTbEditText = "Bland";
        
        /// <summary>
        /// Type '{Tab}' in 'countryTb' text box
        /// </summary>
        public string UICountryTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '9229222' in 'homePhoneTb' text box
        /// </summary>
        public string UIHomePhoneTbEditText = "9229222";
        
        /// <summary>
        /// Type '{Tab}' in 'homePhoneTb' text box
        /// </summary>
        public string UIHomePhoneTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Haybale Representive' in 'titleTb' text box
        /// </summary>
        public string UITitleTbEditText = "Haybale Representive";
        
        /// <summary>
        /// Type '{Tab}' in 'titleTb' text box
        /// </summary>
        public string UITitleTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Select '07-Sep-2010' in 'hireDatePicker' date picker
        /// </summary>
        public string UIHireDatePickerDatePickerDateAsString = "07-Sep-2010";
        
        /// <summary>
        /// Type '2399' in 'extensionTb' text box
        /// </summary>
        public string UIExtensionTbEditText = "2399";
        
        /// <summary>
        /// Type 'John is a crazy man from clove city' in 'notesTb' text box
        /// </summary>
        public string UINotesTbEditText = "John is a crazy man from clove city";
        
        /// <summary>
        /// Type '' in 'reportsToTb' text box
        /// </summary>
        public string UIReportsToTbEditText = "";
        
        /// <summary>
        /// Type '{Tab}' in 'reportsToTb' text box
        /// </summary>
        public string UIReportsToTbEditSendKeys = "{Tab}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddEmployeeTest2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddEmployeeTest2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Jole' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditText = "Jole";
        
        /// <summary>
        /// Type '{Tab}' in 'firstNameTb' text box
        /// </summary>
        public string UIFirstNameTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Smack' in 'lastNameTb' text box
        /// </summary>
        public string UILastNameTbEditText = "Smack";
        
        /// <summary>
        /// Select '11-Sep-1984' in 'birthDatePicker' date picker
        /// </summary>
        public string UIBirthDatePickerDatePickerDateAsString = "11-Sep-1984";
        
        /// <summary>
        /// Type 'Crayon. 21street' in 'addressTb' text box
        /// </summary>
        public string UIAddressTbEditText = "Crayon. 21street";
        
        /// <summary>
        /// Type 'Melon City' in 'cityTb' text box
        /// </summary>
        public string UICityTbEditText = "Melon City";
        
        /// <summary>
        /// Type '{Tab}' in 'cityTb' text box
        /// </summary>
        public string UICityTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'regionTb' text box
        /// </summary>
        public string UIRegionTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '8219' in 'postalCodeTb' text box
        /// </summary>
        public string UIPostalCodeTbEditText = "8219";
        
        /// <summary>
        /// Type '{Tab}' in 'postalCodeTb' text box
        /// </summary>
        public string UIPostalCodeTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Ma land' in 'countryTb' text box
        /// </summary>
        public string UICountryTbEditText = "Ma land";
        
        /// <summary>
        /// Type '{Tab}' in 'countryTb' text box
        /// </summary>
        public string UICountryTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '2891828283838281838' in 'homePhoneTb' text box
        /// </summary>
        public string UIHomePhoneTbEditText = "2891828283838281838";
        
        /// <summary>
        /// Type '{Tab}' in 'homePhoneTb' text box
        /// </summary>
        public string UIHomePhoneTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Melon Representive' in 'titleTb' text box
        /// </summary>
        public string UITitleTbEditText = "Melon Representive";
        
        /// <summary>
        /// Select '05-Jul-2017' in 'hireDatePicker' date picker
        /// </summary>
        public string UIHireDatePickerDatePickerDateAsString = "05-Jul-2017";
        
        /// <summary>
        /// Type '818' in 'extensionTb' text box
        /// </summary>
        public string UIExtensionTbEditText = "818";
        
        /// <summary>
        /// Type '{Tab}' in 'extensionTb' text box
        /// </summary>
        public string UIExtensionTbEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Tab}' in 'reportsToTb' text box
        /// </summary>
        public string UIReportsToTbEditSendKeys = "{Tab}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEmployeeOverwatchWindow : WpfWindow
    {
        
        public UIEmployeeOverwatchWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Employee Overwatch";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Employee Overwatch");
            #endregion
        }
        
        #region Properties
        public UIEmployeeListTable UIEmployeeListTable
        {
            get
            {
                if ((this.mUIEmployeeListTable == null))
                {
                    this.mUIEmployeeListTable = new UIEmployeeListTable(this);
                }
                return this.mUIEmployeeListTable;
            }
        }
        
        public UIPersonligeoplysningeGroup UIPersonligeoplysningeGroup
        {
            get
            {
                if ((this.mUIPersonligeoplysningeGroup == null))
                {
                    this.mUIPersonligeoplysningeGroup = new UIPersonligeoplysningeGroup(this);
                }
                return this.mUIPersonligeoplysningeGroup;
            }
        }
        
        public WpfButton UIGemændringerButton
        {
            get
            {
                if ((this.mUIGemændringerButton == null))
                {
                    this.mUIGemændringerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIGemændringerButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "editBtn";
                    this.mUIGemændringerButton.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIGemændringerButton;
            }
        }
        
        public UIAndreoplysningerGroup UIAndreoplysningerGroup
        {
            get
            {
                if ((this.mUIAndreoplysningerGroup == null))
                {
                    this.mUIAndreoplysningerGroup = new UIAndreoplysningerGroup(this);
                }
                return this.mUIAndreoplysningerGroup;
            }
        }
        
        public WpfButton UISletButton
        {
            get
            {
                if ((this.mUISletButton == null))
                {
                    this.mUISletButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISletButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "deleteBtn";
                    this.mUISletButton.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUISletButton;
            }
        }
        
        public WpfButton UITilføjButton
        {
            get
            {
                if ((this.mUITilføjButton == null))
                {
                    this.mUITilføjButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITilføjButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "addBtn";
                    this.mUITilføjButton.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUITilføjButton;
            }
        }
        #endregion
        
        #region Fields
        private UIEmployeeListTable mUIEmployeeListTable;
        
        private UIPersonligeoplysningeGroup mUIPersonligeoplysningeGroup;
        
        private WpfButton mUIGemændringerButton;
        
        private UIAndreoplysningerGroup mUIAndreoplysningerGroup;
        
        private WpfButton mUISletButton;
        
        private WpfButton mUITilføjButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEmployeeListTable : WpfTable
    {
        
        public UIEmployeeListTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "employeeList";
            this.WindowTitles.Add("Employee Overwatch");
            #endregion
        }
        
        #region Properties
        public WpfControl UIItemDataItem
        {
            get
            {
                if ((this.mUIItemDataItem == null))
                {
                    this.mUIItemDataItem = new WpfControl(this);
                    #region Search Criteria
                    this.mUIItemDataItem.SearchProperties[WpfControl.PropertyNames.ControlType] = "DataItem";
                    this.mUIItemDataItem.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIItemDataItem;
            }
        }
        
        public WpfControl UIItemDataItem1
        {
            get
            {
                if ((this.mUIItemDataItem1 == null))
                {
                    this.mUIItemDataItem1 = new WpfControl(this);
                    #region Search Criteria
                    this.mUIItemDataItem1.SearchProperties[WpfControl.PropertyNames.ControlType] = "DataItem";
                    this.mUIItemDataItem1.SearchProperties[WpfControl.PropertyNames.Instance] = "3";
                    this.mUIItemDataItem1.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIItemDataItem1;
            }
        }
        
        public UIItemDataItem2 UIItemDataItem2
        {
            get
            {
                if ((this.mUIItemDataItem2 == null))
                {
                    this.mUIItemDataItem2 = new UIItemDataItem2(this);
                }
                return this.mUIItemDataItem2;
            }
        }
        
        public WpfControl UIItemDataItem3
        {
            get
            {
                if ((this.mUIItemDataItem3 == null))
                {
                    this.mUIItemDataItem3 = new WpfControl(this);
                    #region Search Criteria
                    this.mUIItemDataItem3.SearchProperties[WpfControl.PropertyNames.ControlType] = "DataItem";
                    this.mUIItemDataItem3.SearchProperties[WpfControl.PropertyNames.Instance] = "11";
                    this.mUIItemDataItem3.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIItemDataItem3;
            }
        }
        #endregion
        
        #region Fields
        private WpfControl mUIItemDataItem;
        
        private WpfControl mUIItemDataItem1;
        
        private UIItemDataItem2 mUIItemDataItem2;
        
        private WpfControl mUIItemDataItem3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemDataItem2 : WpfControl
    {
        
        public UIItemDataItem2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "DataItem";
            this.SearchProperties[WpfControl.PropertyNames.Instance] = "10";
            this.WindowTitles.Add("Employee Overwatch");
            #endregion
        }
        
        #region Properties
        public WpfCell UIItem999Cell
        {
            get
            {
                if ((this.mUIItem999Cell == null))
                {
                    this.mUIItem999Cell = new WpfCell(this);
                    #region Search Criteria
                    this.mUIItem999Cell.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Postnummer";
                    this.mUIItem999Cell.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIItem999Cell;
            }
        }
        #endregion
        
        #region Fields
        private WpfCell mUIItem999Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPersonligeoplysningeGroup : WpfGroup
    {
        
        public UIPersonligeoplysningeGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "groupBox";
            this.WindowTitles.Add("Employee Overwatch");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIFirstNameTbEdit
        {
            get
            {
                if ((this.mUIFirstNameTbEdit == null))
                {
                    this.mUIFirstNameTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "firstNameTb";
                    this.mUIFirstNameTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIFirstNameTbEdit;
            }
        }
        
        public WpfDatePicker UIBirthDatePickerDatePicker
        {
            get
            {
                if ((this.mUIBirthDatePickerDatePicker == null))
                {
                    this.mUIBirthDatePickerDatePicker = new WpfDatePicker(this);
                    #region Search Criteria
                    this.mUIBirthDatePickerDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "birthDatePicker";
                    this.mUIBirthDatePickerDatePicker.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIBirthDatePickerDatePicker;
            }
        }
        
        public WpfEdit UICountryTbEdit
        {
            get
            {
                if ((this.mUICountryTbEdit == null))
                {
                    this.mUICountryTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUICountryTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "countryTb";
                    this.mUICountryTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUICountryTbEdit;
            }
        }
        
        public WpfEdit UIAddressTbEdit
        {
            get
            {
                if ((this.mUIAddressTbEdit == null))
                {
                    this.mUIAddressTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIAddressTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "addressTb";
                    this.mUIAddressTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIAddressTbEdit;
            }
        }
        
        public WpfEdit UIRegionTbEdit
        {
            get
            {
                if ((this.mUIRegionTbEdit == null))
                {
                    this.mUIRegionTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIRegionTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "regionTb";
                    this.mUIRegionTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIRegionTbEdit;
            }
        }
        
        public WpfEdit UICityTbEdit
        {
            get
            {
                if ((this.mUICityTbEdit == null))
                {
                    this.mUICityTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUICityTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "cityTb";
                    this.mUICityTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUICityTbEdit;
            }
        }
        
        public WpfComboBox UIComboBoxComboBox
        {
            get
            {
                if ((this.mUIComboBoxComboBox == null))
                {
                    this.mUIComboBoxComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIComboBoxComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "comboBox";
                    this.mUIComboBoxComboBox.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIComboBoxComboBox;
            }
        }
        
        public WpfEdit UILastNameTbEdit
        {
            get
            {
                if ((this.mUILastNameTbEdit == null))
                {
                    this.mUILastNameTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUILastNameTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "lastNameTb";
                    this.mUILastNameTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUILastNameTbEdit;
            }
        }
        
        public WpfEdit UIPostalCodeTbEdit
        {
            get
            {
                if ((this.mUIPostalCodeTbEdit == null))
                {
                    this.mUIPostalCodeTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPostalCodeTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "postalCodeTb";
                    this.mUIPostalCodeTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIPostalCodeTbEdit;
            }
        }
        
        public WpfEdit UIHomePhoneTbEdit
        {
            get
            {
                if ((this.mUIHomePhoneTbEdit == null))
                {
                    this.mUIHomePhoneTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIHomePhoneTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "homePhoneTb";
                    this.mUIHomePhoneTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIHomePhoneTbEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIFirstNameTbEdit;
        
        private WpfDatePicker mUIBirthDatePickerDatePicker;
        
        private WpfEdit mUICountryTbEdit;
        
        private WpfEdit mUIAddressTbEdit;
        
        private WpfEdit mUIRegionTbEdit;
        
        private WpfEdit mUICityTbEdit;
        
        private WpfComboBox mUIComboBoxComboBox;
        
        private WpfEdit mUILastNameTbEdit;
        
        private WpfEdit mUIPostalCodeTbEdit;
        
        private WpfEdit mUIHomePhoneTbEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAndreoplysningerGroup : WpfGroup
    {
        
        public UIAndreoplysningerGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "groupBox1";
            this.WindowTitles.Add("Employee Overwatch");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITitleTbEdit
        {
            get
            {
                if ((this.mUITitleTbEdit == null))
                {
                    this.mUITitleTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITitleTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "titleTb";
                    this.mUITitleTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUITitleTbEdit;
            }
        }
        
        public WpfDatePicker UIHireDatePickerDatePicker
        {
            get
            {
                if ((this.mUIHireDatePickerDatePicker == null))
                {
                    this.mUIHireDatePickerDatePicker = new WpfDatePicker(this);
                    #region Search Criteria
                    this.mUIHireDatePickerDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "hireDatePicker";
                    this.mUIHireDatePickerDatePicker.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIHireDatePickerDatePicker;
            }
        }
        
        public WpfEdit UIExtensionTbEdit
        {
            get
            {
                if ((this.mUIExtensionTbEdit == null))
                {
                    this.mUIExtensionTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIExtensionTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "extensionTb";
                    this.mUIExtensionTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIExtensionTbEdit;
            }
        }
        
        public WpfEdit UINotesTbEdit
        {
            get
            {
                if ((this.mUINotesTbEdit == null))
                {
                    this.mUINotesTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUINotesTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "notesTb";
                    this.mUINotesTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUINotesTbEdit;
            }
        }
        
        public WpfEdit UIReportsToTbEdit
        {
            get
            {
                if ((this.mUIReportsToTbEdit == null))
                {
                    this.mUIReportsToTbEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIReportsToTbEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "reportsToTb";
                    this.mUIReportsToTbEdit.WindowTitles.Add("Employee Overwatch");
                    #endregion
                }
                return this.mUIReportsToTbEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITitleTbEdit;
        
        private WpfDatePicker mUIHireDatePickerDatePicker;
        
        private WpfEdit mUIExtensionTbEdit;
        
        private WpfEdit mUINotesTbEdit;
        
        private WpfEdit mUIReportsToTbEdit;
        #endregion
    }
}
